/**
 * Client-side Markdown export for an A/B comparison (AbReport shape).
 *
 * Pure assembly over the already-loaded report — no backend. Leads with the
 * verdict + the pre-formatted `ship_list[].markdown` (which the backend already
 * produced as paste-ready tracker lines but the UI never exposed), then the
 * segment leanings and top lever combinations.
 */

import type { AbReport } from "@/types/ab-report";

function actionLabel(a: string): string {
  if (a === "keep") return "KEEP";
  if (a === "kill") return "KILL";
  if (a === "revisit") return "REVISIT";
  return a.toUpperCase();
}

export function abReportToMarkdown(data: AbReport, name?: string): string {
  const lines: string[] = [];
  const meta = data.meta;
  const title = name || meta?.study_name || "A/B Comparison";
  const date = meta?.generated_at
    ? new Date(meta.generated_at).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "";

  lines.push(`# ${title} — A/B Comparison`);
  lines.push(
    `_${[date, meta?.persona_count ? `${meta.persona_count} personas` : "", meta?.runs_per_persona ? `${meta.runs_per_persona} runs each` : ""]
      .filter(Boolean)
      .join(" · ")}_`,
  );
  lines.push("");

  // Verdict
  if (data.verdict?.sentence) {
    lines.push(`## Verdict (${data.verdict.confidence} confidence)`);
    lines.push(data.verdict.sentence);
    lines.push("");
  }

  // What to ship — reuse the pre-formatted markdown lines.
  if (data.ship_list?.length) {
    lines.push(`## What to ship`);
    for (const s of data.ship_list) {
      if (s.markdown && s.markdown.trim()) {
        lines.push(s.markdown.trim());
      } else {
        lines.push(`- [${actionLabel(s.action)}] ${s.feature} — ${s.rationale}`);
      }
    }
    lines.push("");
  }

  // Who preferred what
  if (data.persona_split?.length) {
    lines.push(`## Who preferred what`);
    for (const p of data.persona_split) {
      const winner =
        p.preferred_variant === "neither" ? "no clear winner" : `prefers ${p.preferred_variant}`;
      lines.push(
        `- **${p.segment}** (${p.persona_count}) → ${winner}${p.interpretation ? `: ${p.interpretation}` : ""}`,
      );
    }
    lines.push("");
  }

  // Top lever combinations
  const combos = data.lever_attribution?.top_combinations ?? [];
  if (combos.length) {
    lines.push(`## Top lever combinations`);
    for (const c of combos.slice(0, 8)) {
      const delta = `${c.delta_vs_baseline >= 0 ? "+" : ""}${Math.round(c.delta_vs_baseline * 100)}pp`;
      lines.push(
        `- Variant ${c.variant} · ${c.levers.join(" + ")} (${c.persona_count}p): ${Math.round(c.convert_rate * 100)}% convert, ${delta} vs baseline${c.interpretation ? ` — ${c.interpretation}` : ""}`,
      );
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by Apriori — synthetic-user A/B simulation._`);
  return lines.join("\n");
}
