/**
 * Client-side export for a finished single-flow simulation.
 *
 * v1 is pure assembly over the already-loaded SimulationData blob — no backend,
 * no recompute. Produces a forwardable Markdown decision memo and a per-persona
 * × per-screen CSV. Everything is optional-chained so legacy/partial blobs still
 * export something useful.
 */

import type { SimulationData, DecisionVerdict } from "@/types/simulation";

const VERDICT_LABEL: Record<DecisionVerdict, string> = {
  ship: "SHIP IT",
  fix_first: "FIX FIRST",
  hold: "HOLD",
};

function titleCaseScreen(id: string): string {
  const m = id.match(/view_(\d+)/i);
  if (m) return `Screen ${m[1]}`;
  return id.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Build a Markdown decision memo a PM can paste into Notion / Slack / a doc. */
export function simulationToMarkdown(data: SimulationData, name?: string): string {
  const lines: string[] = [];
  const title = name || data.flow_name || "Simulation Report";
  const s = data.summary;
  const date = data.generated_at
    ? new Date(data.generated_at).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "";

  lines.push(`# ${title} — Simulation Report`);
  lines.push(
    `_${[date, `${s.total_personas} personas`, `${s.completion_rate_pct}% completion`]
      .filter(Boolean)
      .join(" · ")}_`,
  );
  lines.push("");

  // Decision brief
  const brief = data.decision_brief;
  if (brief) {
    lines.push(`## Decision: ${VERDICT_LABEL[brief.verdict_label] ?? brief.verdict_label}`);
    if (brief.overall_verdict) lines.push(brief.overall_verdict);
    lines.push("");
    const cal = brief.calibration
      ? ` (${brief.calibration.delta_pp >= 0 ? "+" : ""}${brief.calibration.delta_pp}pp vs ${brief.calibration.expected_completion_rate_pct}% real-world)`
      : "";
    lines.push(`- **Completion:** ${brief.completion_rate_pct}%${cal}`);
    if (brief.headline_barrier) {
      const b = brief.headline_barrier;
      lines.push(
        `- **Biggest barrier:** ${titleCaseScreen(b.screen)} (${b.drop_off_pct}% drop)${b.reason ? ` — ${b.reason}` : ""}`,
      );
    }
    if (brief.worst_segment) {
      const w = brief.worst_segment;
      lines.push(
        `- **Most-affected segment:** ${w.segment} (${w.completion_pct}% complete)${w.top_drop_off_reason ? ` — ${w.top_drop_off_reason}` : ""}`,
      );
    }
    if (brief.top_fix) {
      const f = brief.top_fix;
      lines.push(
        `- **Do this first:** ${f.recommendation}${f.expected_uplift ? ` (${f.expected_uplift})` : ""}`,
      );
    }
    lines.push("");
    if (brief.confidence_note) {
      lines.push(`> ${brief.confidence_note}`);
      lines.push("");
    }
  } else if (data.flow_assessment?.overall_verdict) {
    lines.push(`## Verdict`);
    lines.push(data.flow_assessment.overall_verdict);
    lines.push("");
  }

  // Objective alignment
  if (typeof s.objective_match_rate_pct === "number") {
    lines.push(`## Against your objective`);
    lines.push(
      `**${s.objective_match_rate_pct}%** of personas met the objective (vs ${s.completion_rate_pct}% who completed the flow).`,
    );
    lines.push("");
  }

  // Ranked fixes
  const fixes = data.fix_recommendations || data.flow_assessment?.fix_recommendations || [];
  if (fixes.length > 0) {
    lines.push(`## Ranked fixes`);
    fixes.forEach((f, i) => {
      lines.push(
        `${i + 1}. **[${f.estimated_impact} impact / ${f.feasibility} feasibility]** ${f.recommendation}${f.screen ? ` — _${titleCaseScreen(f.screen)}_` : ""}${f.expected_uplift ? ` (${f.expected_uplift})` : ""}`,
      );
      if (f.root_cause) lines.push(`   - Root cause: ${f.root_cause}`);
      if (f.affected_segment) lines.push(`   - Affects: ${f.affected_segment}`);
      (f.marginal_driver_quotes ?? []).forEach((q) =>
        lines.push(`   - Would have flipped them: "${q}"`),
      );
    });
    lines.push("");
  }

  // Top drop-off reasons (clustered)
  const screens = data.drop_off_analysis?.screens || {};
  const clusterRows: string[] = [];
  for (const [sid, sdata] of Object.entries(screens)) {
    (sdata.clusters || []).forEach((c) => {
      if (c.label) {
        clusterRows.push(
          `- **${titleCaseScreen(sid)}** — ${c.label}${typeof c.persona_count === "number" ? ` (${c.persona_count})` : ""}${c.representative_reasoning ? `: "${c.representative_reasoning}"` : ""}`,
        );
      }
    });
  }
  if (clusterRows.length > 0) {
    lines.push(`## Top drop-off reasons`);
    lines.push(...clusterRows.slice(0, 12));
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by Apriori — synthetic-user simulation._`);
  return lines.join("\n");
}

function csvCell(v: unknown): string {
  const s = v === null || v === undefined ? "" : String(v);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

/** Per-persona × per-screen rows: one row per screen each persona saw. */
export function simulationToCSV(data: SimulationData): string {
  const header = [
    "persona_uuid",
    "archetype",
    "occupation",
    "age",
    "outcome",
    "screen_id",
    "view_name",
    "decision_outcome",
    "trust",
    "clarity",
    "value",
    "time_s",
    "friction_points",
    "selected_choice",
  ];
  const rows: string[][] = [header];

  for (const p of data.persona_details || []) {
    const demo = p.demographics || {};
    const base = [
      p.persona_uuid,
      String(demo.behavioral_archetype ?? ""),
      String(demo.occupation ?? ""),
      String(demo.age ?? ""),
      p.outcome,
    ];
    const monos = p.screen_monologues || [];
    if (monos.length === 0) {
      rows.push([...base, "", "", "", "", "", "", "", "", ""]);
      continue;
    }
    for (const m of monos) {
      rows.push([
        ...base,
        m.screen_id,
        m.view_name,
        m.decision_outcome,
        String(m.trust_score ?? ""),
        String(m.clarity_score ?? ""),
        String(m.value_score ?? ""),
        String(m.time_seconds ?? ""),
        (m.friction_points || []).join("; "),
        m.selected_choice ?? "",
      ]);
    }
  }

  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

/** Await the clipboard write so callers can show success only on real success. */
export async function copyToClipboard(text: string): Promise<void> {
  if (!navigator?.clipboard?.writeText) {
    throw new Error("Clipboard not available");
  }
  await navigator.clipboard.writeText(text);
}

export function downloadFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function safeFilename(name: string): string {
  return (name || "simulation").replace(/[^a-z0-9-_]+/gi, "_").slice(0, 60);
}
