import type { PersonaReaction, PatternInsight } from './types';

const PERSONA_POOL = [
  { persona_id: 'p1', persona_name: 'Priya M.', occupation: 'Manager, Import & Export', income_tier: 'high' as const, digital_literacy: 8, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'mobile' as const },
  { persona_id: 'p2', persona_name: 'Ramesh K.', occupation: 'Freelancer, Logistics', income_tier: 'mid' as const, digital_literacy: 6, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'both' as const },
  { persona_id: 'p3', persona_name: 'Sunita D.', occupation: 'SME Owner, Textiles', income_tier: 'mid' as const, digital_literacy: 5, vulnerability_level: 'low' as const, geography_type: 'rural' as const, device_type: 'mobile' as const },
  { persona_id: 'p4', persona_name: 'Vikram S.', occupation: 'Accountant', income_tier: 'high' as const, digital_literacy: 7, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'desktop' as const },
  { persona_id: 'p5', persona_name: 'Lakshmi P.', occupation: 'Homemaker, Side Business', income_tier: 'low' as const, digital_literacy: 3, vulnerability_level: 'high' as const, geography_type: 'rural' as const, device_type: 'mobile' as const },
  { persona_id: 'p6', persona_name: 'Arjun T.', occupation: 'Export Coordinator', income_tier: 'high' as const, digital_literacy: 9, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'both' as const },
  { persona_id: 'p7', persona_name: 'Kavita R.', occupation: 'Office Admin', income_tier: 'mid' as const, digital_literacy: 5, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'mobile' as const },
  { persona_id: 'p8', persona_name: 'Suresh M.', occupation: 'Driver, Part-time Seller', income_tier: 'low' as const, digital_literacy: 2, vulnerability_level: 'high' as const, geography_type: 'rural' as const, device_type: 'mobile' as const },
  { persona_id: 'p9', persona_name: 'Anita G.', occupation: 'Consultant', income_tier: 'high' as const, digital_literacy: 8, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'desktop' as const },
  { persona_id: 'p10', persona_name: 'Rajesh N.', occupation: 'Shop Owner', income_tier: 'mid' as const, digital_literacy: 4, vulnerability_level: 'low' as const, geography_type: 'rural' as const, device_type: 'mobile' as const },
  { persona_id: 'p11', persona_name: 'Meera V.', occupation: 'Teacher, Reseller', income_tier: 'mid' as const, digital_literacy: 6, vulnerability_level: 'low' as const, geography_type: 'urban' as const, device_type: 'both' as const },
  { persona_id: 'p12', persona_name: 'Deepak C.', occupation: 'Retired, Small Trader', income_tier: 'low' as const, digital_literacy: 2, vulnerability_level: 'high' as const, geography_type: 'rural' as const, device_type: 'mobile' as const },
];

function buildReaction(
  adId: string,
  persona: typeof PERSONA_POOL[0],
  overrides: Partial<Omit<PersonaReaction, 'persona_id' | 'occupation' | 'income_tier' | 'digital_literacy' | 'vulnerability_level' | 'geography_type' | 'device_type'>>,
): PersonaReaction {
  return {
    persona_id: persona.persona_id,
    persona_name: persona.persona_name,
    occupation: persona.occupation,
    income_tier: persona.income_tier,
    digital_literacy: persona.digital_literacy,
    vulnerability_level: persona.vulnerability_level,
    geography_type: persona.geography_type,
    device_type: persona.device_type,
    decision: 'viewed_no_click',
    high_intent: false,
    trust_score: 5,
    relevance_score: 5,
    confidence_score: 0.85,
    positive_triggers: [],
    negative_frictions: [],
    trust_drivers: [],
    trust_breakers: [],
    initial_impression: '',
    decision_driver: '',
    risk_flag: false,
    ...overrides,
  };
}

export function getReactionsForAd(adId: string): PersonaReaction[] {
  const p = PERSONA_POOL;
  const reactions: PersonaReaction[] = [
    buildReaction(adId, p[0], {
      decision: 'clicked_high_intent',
      high_intent: true,
      trust_score: 8,
      relevance_score: 7,
      confidence_score: 0.92,
      click_probability: 0.88,
      positive_triggers: ['Local language (Hindi)', 'Certification badge', 'Relevant pain point'],
      negative_frictions: [],
      trust_drivers: ['Hindi copy', 'Certification visible', 'Professional layout'],
      trust_breakers: [],
      initial_impression: 'Felt relevant and legitimate immediately.',
      decision_driver: 'Language match and trust signals led to click.',
      risk_flag: false,
    }),
    buildReaction(adId, p[1], {
      decision: 'clicked_high_intent',
      high_intent: true,
      trust_score: 7.5,
      relevance_score: 7,
      confidence_score: 0.89,
      click_probability: 0.82,
      positive_triggers: ['Clear value proposition', 'Familiar brand elements'],
      negative_frictions: ['Slightly long copy'],
      trust_drivers: ['Professional imagery', 'Clear CTA'],
      trust_breakers: [],
      initial_impression: 'Clear and professional; matched my needs.',
      decision_driver: 'Relevance to logistics and export.',
      risk_flag: false,
    }),
    buildReaction(adId, p[2], {
      decision: 'clicked_low_intent',
      high_intent: false,
      trust_score: 6,
      relevance_score: 5.5,
      confidence_score: 0.84,
      click_probability: 0.55,
      positive_triggers: ['Regional language option'],
      negative_frictions: ['Unclear if applicable to rural'],
      trust_drivers: ['Local language'],
      trust_breakers: ['Generic imagery'],
      initial_impression: 'Interesting but not sure it applies to me.',
      decision_driver: 'Curiosity; wanted to check eligibility.',
      risk_flag: false,
    }),
    buildReaction(adId, p[3], {
      decision: 'viewed_no_click',
      high_intent: false,
      trust_score: 5.5,
      relevance_score: 5,
      confidence_score: 0.86,
      click_probability: 0.35,
      positive_triggers: ['Clean layout'],
      negative_frictions: ['No clear differentiation', 'Seen similar ads before'],
      trust_drivers: [],
      trust_breakers: ['Generic messaging'],
      initial_impression: 'Neutral; did not feel urgent or specific.',
      decision_driver: 'Lack of clear benefit for my role.',
      risk_flag: false,
    }),
    buildReaction(adId, p[4], {
      decision: 'high_vulnerability',
      high_intent: false,
      trust_score: 4,
      relevance_score: 3,
      confidence_score: 0.78,
      click_probability: 0.2,
      positive_triggers: [],
      negative_frictions: ['Too many claims', 'Unclear pricing'],
      trust_drivers: [],
      trust_breakers: ['Promotional tone', 'Vague guarantees'],
      initial_impression: 'Felt pushy; worried about scams.',
      decision_driver: 'High vulnerability; avoided engagement.',
      risk_flag: true,
    }),
    buildReaction(adId, p[5], {
      decision: 'clicked_high_intent',
      high_intent: true,
      trust_score: 8.5,
      relevance_score: 8,
      confidence_score: 0.93,
      click_probability: 0.9,
      positive_triggers: ['Trust signals', 'Language', 'Relevance'],
      negative_frictions: [],
      trust_drivers: ['Certification', 'Professional design', 'Specific offer'],
      trust_breakers: [],
      initial_impression: 'Highly relevant; trusted source.',
      decision_driver: 'Strong alignment with export role.',
      risk_flag: false,
    }),
    buildReaction(adId, p[6], {
      decision: 'viewed_no_click',
      high_intent: false,
      trust_score: 5,
      relevance_score: 5,
      confidence_score: 0.82,
      click_probability: 0.3,
      positive_triggers: [],
      negative_frictions: ['Too long', 'Unclear CTA'],
      trust_drivers: [],
      trust_breakers: ['Generic'],
      initial_impression: 'Scanned and moved on.',
      decision_driver: 'No compelling reason to click.',
      risk_flag: false,
    }),
    buildReaction(adId, p[7], {
      decision: 'rejected',
      high_intent: false,
      trust_score: 3,
      relevance_score: 2,
      confidence_score: 0.8,
      click_probability: 0.05,
      positive_triggers: [],
      negative_frictions: ['Suspicious claims', 'Too good to be true'],
      trust_drivers: [],
      trust_breakers: ['Aggressive copy', 'No verification visible'],
      initial_impression: 'Did not trust; skipped.',
      decision_driver: 'Negative reaction to tone and claims.',
      risk_flag: true,
    }),
    buildReaction(adId, p[8], {
      decision: 'clicked_high_intent',
      high_intent: true,
      trust_score: 7.8,
      relevance_score: 7.5,
      confidence_score: 0.9,
      click_probability: 0.85,
      positive_triggers: ['Professional', 'Clear value'],
      negative_frictions: [],
      trust_drivers: ['Design', 'Credentials'],
      trust_breakers: [],
      initial_impression: 'Credible and relevant to consulting.',
      decision_driver: 'Trust and relevance.',
      risk_flag: false,
    }),
    buildReaction(adId, p[9], {
      decision: 'viewed_no_click',
      high_intent: false,
      trust_score: 4.5,
      relevance_score: 4,
      confidence_score: 0.81,
      click_probability: 0.25,
      positive_triggers: [],
      negative_frictions: ['English only', 'Urban focus'],
      trust_drivers: [],
      trust_breakers: ['Not localized'],
      initial_impression: 'Felt more for city businesses.',
      decision_driver: 'Segment mismatch.',
      risk_flag: false,
    }),
    buildReaction(adId, p[10], {
      decision: 'clicked_low_intent',
      high_intent: false,
      trust_score: 6.5,
      relevance_score: 6,
      confidence_score: 0.87,
      click_probability: 0.5,
      positive_triggers: ['Relatable scenario'],
      negative_frictions: ['Wanted more proof'],
      trust_drivers: ['Social proof hint'],
      trust_breakers: [],
      initial_impression: 'Moderately interested; would need more info.',
      decision_driver: 'Curiosity about reseller angle.',
      risk_flag: false,
    }),
    buildReaction(adId, p[11], {
      decision: 'high_vulnerability',
      high_intent: false,
      trust_score: 3.5,
      relevance_score: 2.5,
      confidence_score: 0.76,
      click_probability: 0.08,
      positive_triggers: [],
      negative_frictions: ['Confusing', 'Fear of scam'],
      trust_drivers: [],
      trust_breakers: ['Complex language', 'Too many promises'],
      initial_impression: 'Confusing and worrying.',
      decision_driver: 'Vulnerability; avoided.',
      risk_flag: true,
      counterfactual: {
        change: 'Simplify copy and add single clear guarantee',
        probability_before: 0.08,
        probability_after: 0.22,
      },
    }),
  ];

  return reactions;
}

export function getPatternInsightsForAd(adId: string, _filteredCount: number): PatternInsight[] {
  return [
    { id: '1', label: 'Local language drives clicks', type: 'click_reason', persona_count: 4, confidence: 0.91, statistically_significant: true, description: 'Personas with Hindi or regional language preference showed higher click rate.' },
    { id: '2', label: 'Certification badge increases trust', type: 'click_reason', persona_count: 5, confidence: 0.88, statistically_significant: true, description: 'Trust drivers frequently cite certification or verification elements.' },
    { id: '3', label: 'Generic messaging causes skip', type: 'rejection_cause', persona_count: 3, confidence: 0.85, statistically_significant: true, description: 'Viewed-but-did-not-click personas cite lack of differentiation.' },
    { id: '4', label: 'Rural segment mismatch', type: 'segment_mismatch', persona_count: 2, confidence: 0.82, statistically_significant: false, description: 'Rural personas report ad feels urban-focused.' },
    { id: '5', label: 'High vulnerability risk', type: 'risk_signal', persona_count: 2, confidence: 0.9, statistically_significant: true, description: 'High-vulnerability personas show negative reaction and risk flag.' },
    { id: '6', label: 'Low literacy friction', type: 'literacy_mismatch', persona_count: 2, confidence: 0.79, statistically_significant: false, description: 'Low digital literacy personas report confusing or pushy copy.' },
    { id: '7', label: 'Claim sensitivity', type: 'claim_sensitivity', persona_count: 3, confidence: 0.84, statistically_significant: true, description: 'Strong or vague claims trigger trust breakers for some segments.' },
  ];
}
