/**
 * Canonical A/B report schema — used by BOTH single-screen and full-flow A/B.
 *
 * The only structural difference between modes is `annotated_screens.screens.length`:
 *   single-screen → 1 entry
 *   full-flow     → N entries (one per screen pair)
 *
 * The backend (`backend/src/api/models/ab_report.py`) emits this shape on the
 * `comparison_ready` NDJSON event. The frontend renders it via `AbReportView`.
 */

export type Confidence = "high" | "medium" | "low";
export type Severity = "critical" | "high" | "medium" | "low";
export type VariantTag = "A" | "B" | "both" | "neither";
export type ElementVerdict = "lift" | "drag" | "tradeoff";
export type ShipAction = "keep" | "kill" | "revisit";
export type DecisionOutcome = "convert" | "hesitate" | "abandon";
export type LeaningTag = "A" | "B" | "neither";

export interface ReportMeta {
  /** UUID generated by the backend at run start. Used as the persistence key
   * (`public.simulations.simulation_id`) and the routing slug for `/simulations/...`. */
  simulation_id: string;
  study_name: string;
  client: string;
  /** Single-screen: the one screen's label. Full-flow: descriptor like "5-screen onboarding". */
  screen_label: string;
  persona_count: number;
  runs_per_persona: number;
  /** ISO-8601 UTC timestamp. */
  generated_at: string;
}

export interface Verdict {
  sentence: string;
  confidence: Confidence;
}

export interface ShipItem {
  id: string;
  action: ShipAction;
  source_variant: VariantTag;
  feature: string;
  rationale: string;
  bullet: string;
  confidence: Confidence;
  /** Pre-formatted markdown checkbox line — pasted directly into a tracker. */
  markdown: string;
}

/** Normalized 0..1 anchor for a callout overlay on a screenshot. */
export interface Anchor {
  x: number;
  y: number;
}

export interface ScreenElement {
  id: string;
  label: string;
  anchor: Anchor;
  verdict: ElementVerdict;
  callout: string;
  persona_count: number;
  summary: string;
}

export interface AnnotatedVariant {
  image_path: string;
  elements: ScreenElement[];
}

/**
 * One paired-screen entry. For a single-screen study there is exactly one of these.
 * For a full-flow A/B, there is one per screen index in the journey.
 */
export interface AnnotatedScreenPair {
  /** Stable id (e.g. "screen-1", "trial-activation"). */
  id: string;
  /** Index in the flow, 0-based. Always 0 for single-screen. */
  index: number;
  /** Human label e.g. "Trial activation screen" or "Step 3 — KYC". */
  screen_label: string;
  variant_a: AnnotatedVariant;
  variant_b: AnnotatedVariant;
  /**
   * Auto-extracted design knobs that vary between variants A and B on this
   * screen. Empty when this screen had no inventory (legacy reports or
   * extraction failure). Drives the Lever Analysis tab.
   */
  levers?: Lever[];
}

export interface AnnotatedScreens {
  screens: AnnotatedScreenPair[];
}

export interface ReactionItem {
  name: string;
  source: VariantTag;
}

export interface PersonaReactions {
  loved: ReactionItem[];
  disliked: ReactionItem[];
  tolerated?: ReactionItem[];
  mixed?: ReactionItem[];
  needs?: ReactionItem[];
}

export interface PersonaSplit {
  segment: string;
  persona_count: number;
  preferred_variant: LeaningTag;
  reactions: PersonaReactions;
  interpretation: string;
}

export interface FrictionItem {
  type: string;
  severity: Severity;
  persona_count: number;
  note: string;
}

export interface FrictionProvenance {
  variant_a: FrictionItem[];
  variant_b: FrictionItem[];
}

export interface MonologueDiff {
  persona_id: string;
  persona_name: string;
  segment: string;
  variant_a_monologue: string;
  variant_b_monologue: string;
  inflection: string;
  decision_a: DecisionOutcome;
  decision_b: DecisionOutcome;
}

export interface PersonaVariantExperience {
  outcome: DecisionOutcome;
  monologue: string;
  primary_emotion: string;
  why: string;
  liked: string[];
  disliked: string[];
}

export interface PersonaDeepDive {
  id: string;
  name: string;
  segment: string;
  archetype: string;
  occupation: string;
  age: number;
  city: string;
  income_band: string;
  tags: string[];
  behavior_summary: string;
  variant_a: PersonaVariantExperience;
  variant_b: PersonaVariantExperience;
  overall_reflection: {
    text: string;
    leaning: LeaningTag;
  };
}

export interface DeepDive {
  personas: PersonaDeepDive[];
}

/* ── Lever inventory + attribution ───────────────────────────────────────── */

export type LeverCategory = "copy" | "cta" | "imagery" | "layout" | "color" | "content";
export type LeverValence = "loved" | "liked" | "neutral" | "disliked" | "missed";

/** Auto-extracted design knob that varies between variant A and B on a screen. */
export interface Lever {
  lever_id: string;
  label: string;
  category: LeverCategory;
  variant_a_value: string;
  variant_b_value: string;
  anchor_a: Anchor;
  anchor_b: Anchor;
}

/** One row of the combinatorial lever-attribution table. */
export interface LeverCombination {
  levers: string[];               // lever_ids, sorted, ≤3 entries
  variant: "A" | "B";
  persona_count: number;
  convert_rate: number;           // 0..1
  delta_vs_baseline: number;      // [-1, 1]
  cohort: string | null;          // null = global row
  interpretation: string;
}

export interface LeverAttribution {
  top_combinations: LeverCombination[];          // ≤10, sorted by |delta|
  by_segment: Record<string, LeverCombination[]>;
  notes: string;
}

/**
 * The full A/B report payload. Emitted on `comparison_ready` and persisted
 * to `public.simulations.result`.
 */
export interface AbReport {
  meta: ReportMeta;
  verdict: Verdict;
  ship_list: ShipItem[];
  annotated_screens: AnnotatedScreens;
  persona_split: PersonaSplit[];
  friction_provenance: FrictionProvenance;
  monologue_diff: MonologueDiff[];
  deep_dive?: DeepDive;
  /** Combinatorial lever analysis. Null when the run had no lever inventory. */
  lever_attribution?: LeverAttribution | null;
}

/**
 * simul2design Multiverse Synthesis Engine output. Emitted ~4-5 min AFTER
 * `comparison_ready` on the `synthesis_ready` SSE event when the backend's
 * `SIMUL2DESIGN_ENABLED` flag is on. Mirrors `simul2design/schemas.py::SynthesisResult`.
 *
 * The cascade turns the AbReport into a buildable V(N+1) spec (markdown +
 * structured JSON) and renders a phone-frame PNG via Playwright. The PNG is
 * uploaded to Supabase Storage; `variant_image_url` carries the CDN URL.
 */
export interface SynthesisResultCellRef {
  variant_id: string;
  dimension: string;
  /** "low_default" | "needs_review" | "auto_mapped_llm" | "high" */
  confidence: string;
  current_value: unknown;
}

export interface SynthesisResultTokenUsage {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens: number;
  cache_write_tokens: number;
}

export interface SynthesisResult {
  client_slug: string;
  pipeline_version: string;
  element_matrix: Record<string, unknown>;
  automap_trace: Record<string, unknown>;
  source_markdown: string;
  cells_needing_review: SynthesisResultCellRef[];
  ready_for_synthesis: boolean;
  estimated_cost_usd: number;
  token_usage: SynthesisResultTokenUsage;
  /** Phase 3c outputs — populated when run_full_cascade=True (our default). */
  weighted_scores: Record<string, unknown> | null;
  synthesized_variant: Record<string, unknown> | null;
  adversary_review: Record<string, unknown> | null;
  conversion_estimates: Record<string, unknown> | null;
  spec_markdown: string | null;
  /** Reserved upstream — never populated today. */
  report_html: string | null;
  /** v0.2.0 render — Playwright-rendered PNG of the V(N+1) screen. */
  variant_image_path?: string | null;
  variant_image_size_bytes?: number | null;
  /** Supabase Storage CDN URL set by our orchestrator after a successful upload. Null
   * when the render extra is missing, render failed, or upload errored. */
  variant_image_url?: string | null;
}

/**
 * The full payload of a `synthesis_ready` SSE event AND the shape persisted
 * server-side to `public.simulations.synthesis`.
 */
export interface SynthesisReadyData {
  synthesis_input_source: "ab_report" | "comparison_data";
  ready_for_human: boolean;
  /** Top-level convenience copy of result.variant_image_url. Null when render
   * or upload didn't produce a URL. */
  variant_image_url: string | null;
  result: SynthesisResult;
}

/**
 * Lever-driven design combiner output. Emitted ~2 min AFTER
 * `comparison_ready` on the `design_combiner_ready` SSE event when the
 * backend's `APRIORI_DESIGN_COMBINER_ENABLED` flag is on.
 *
 * The combiner takes the AbReport's lever_attribution (winning levers per
 * variant + interaction probe + Simpson flags) and Opus 4.5 paints a fused
 * HTML+PNG variant honouring the empirical signal. The PNG is uploaded to
 * Supabase Storage; `combined_variant_image_url` carries the CDN URL the frontend
 * renders directly.
 *
 * Distinct from `synthesis` (simul2design cascade) — both can coexist on
 * one simulation row.
 */
export interface DesignCombinerInputSummary {
  control_variant: string;
  device_type: "MOBILE" | "DESKTOP" | "TABLET" | "AGNOSTIC";
  winning_elements_a: number;
  winning_elements_b: number;
  instructions_chars: number;
}

export interface DesignCombinerResult {
  status: "ok" | "failed" | "skipped";
  backend: "claude" | "stitch";
  output_dir: string;
  primary_html_path: string | null;
  primary_png_path: string | null;
  summary_path: string | null;
  prompt_path: string | null;
  validation: Record<string, unknown> | null;
  describer: Record<string, unknown> | null;
  generator: Record<string, unknown> | null;
  validator: Record<string, unknown> | null;
  cost_usd: number;
  elapsed_seconds: number;
  error: string | null;
}

export interface DesignCombinerReadyData {
  comparison_id: string;
  client: string;
  /** Supabase Storage CDN URL of the fused variant PNG. The frontend should render
   * this directly via <img src={...}>. Null when Supabase Storage upload failed
   * (the local primary_png_path on the backend is still readable for
   * debugging, but won't be reachable from the browser). */
  combined_variant_image_url: string | null;
  /** The full combiner result dict — paths, cost, validation iters,
   * token usage. Useful for debug panels but not required to render the
   * combined variant. */
  result: DesignCombinerResult;
  input_summary: DesignCombinerInputSummary;
}

/**
 * Pro-tier revalidation output. Emitted on `revalidation_ready` after the
 * design combiner when `APRIORI_LEVER_REVALIDATE_ENABLED=1`. Re-simulates
 * the fused variant against the same persona pool and compares its
 * completion rate to the better of A/B.
 */
export interface RevalidationReadyData {
  comparison_id: string;
  combined_variant_image_url: string | null;
  completion_rate_a: number;
  completion_rate_b: number;
  completion_rate_combined: number;
  completion_rate_winner: number;
  /** combined - winner. Positive = the fused variant beat the better source. */
  validated_lift: number;
  num_personas: number;
  /** Single-screen revalidation insights (same shape as a regular flow run
   * but with one TERMINAL node). Useful for "drilldown into the
   * revalidation personas" panels. */
  insights: Record<string, unknown>;
}
