/**
 * Canonical A/B report schema — used by BOTH single-screen and full-flow A/B.
 *
 * The only structural difference between modes is `annotated_screens.screens.length`:
 *   single-screen → 1 entry
 *   full-flow     → N entries (one per screen pair)
 *
 * The backend (`backend/src/api/models/ab_report.py`) emits this shape on the
 * `comparison_ready` NDJSON event. The frontend renders it via `AbReportView`.
 */

export type Confidence = "high" | "medium" | "low";
export type Severity = "critical" | "high" | "medium" | "low";
export type VariantTag = "A" | "B" | "both" | "neither";
export type ElementVerdict = "lift" | "drag" | "tradeoff";
export type ShipAction = "keep" | "kill" | "revisit";
export type DecisionOutcome = "convert" | "hesitate" | "abandon";
export type LeaningTag = "A" | "B" | "neither";

export interface ReportMeta {
  /** UUID generated by the backend at run start. Used as the persistence key
   * (`public.simulations.simulation_id`) and the routing slug for `/simulations/...`. */
  simulation_id: string;
  study_name: string;
  client: string;
  /** Single-screen: the one screen's label. Full-flow: descriptor like "5-screen onboarding". */
  screen_label: string;
  persona_count: number;
  runs_per_persona: number;
  /** ISO-8601 UTC timestamp. */
  generated_at: string;
}

export interface Verdict {
  sentence: string;
  confidence: Confidence;
}

export interface ShipItem {
  id: string;
  action: ShipAction;
  source_variant: VariantTag;
  feature: string;
  rationale: string;
  bullet: string;
  confidence: Confidence;
  /** Pre-formatted markdown checkbox line — pasted directly into a tracker. */
  markdown: string;
}

/** Normalized 0..1 anchor for a callout overlay on a screenshot. */
export interface Anchor {
  x: number;
  y: number;
}

export interface ScreenElement {
  id: string;
  label: string;
  anchor: Anchor;
  verdict: ElementVerdict;
  callout: string;
  persona_count: number;
  summary: string;
}

export interface AnnotatedVariant {
  image_path: string;
  elements: ScreenElement[];
}

/**
 * One paired-screen entry. For a single-screen study there is exactly one of these.
 * For a full-flow A/B, there is one per screen index in the journey.
 */
export interface AnnotatedScreenPair {
  /** Stable id (e.g. "screen-1", "trial-activation"). */
  id: string;
  /** Index in the flow, 0-based. Always 0 for single-screen. */
  index: number;
  /** Human label e.g. "Trial activation screen" or "Step 3 — KYC". */
  screen_label: string;
  variant_a: AnnotatedVariant;
  variant_b: AnnotatedVariant;
}

export interface AnnotatedScreens {
  screens: AnnotatedScreenPair[];
}

export interface ReactionItem {
  name: string;
  source: VariantTag;
}

export interface PersonaReactions {
  loved: ReactionItem[];
  disliked: ReactionItem[];
  tolerated?: ReactionItem[];
  mixed?: ReactionItem[];
  needs?: ReactionItem[];
}

export interface PersonaSplit {
  segment: string;
  persona_count: number;
  preferred_variant: LeaningTag;
  reactions: PersonaReactions;
  interpretation: string;
}

export interface FrictionItem {
  type: string;
  severity: Severity;
  persona_count: number;
  note: string;
}

export interface FrictionProvenance {
  variant_a: FrictionItem[];
  variant_b: FrictionItem[];
}

export interface MonologueDiff {
  persona_id: string;
  persona_name: string;
  segment: string;
  variant_a_monologue: string;
  variant_b_monologue: string;
  inflection: string;
  decision_a: DecisionOutcome;
  decision_b: DecisionOutcome;
}

export interface PersonaVariantExperience {
  outcome: DecisionOutcome;
  monologue: string;
  primary_emotion: string;
  why: string;
  liked: string[];
  disliked: string[];
}

export interface PersonaDeepDive {
  id: string;
  name: string;
  segment: string;
  archetype: string;
  occupation: string;
  age: number;
  city: string;
  income_band: string;
  tags: string[];
  behavior_summary: string;
  variant_a: PersonaVariantExperience;
  variant_b: PersonaVariantExperience;
  overall_reflection: {
    text: string;
    leaning: LeaningTag;
  };
}

export interface DeepDive {
  personas: PersonaDeepDive[];
}

/**
 * The full A/B report payload. Emitted on `comparison_ready` and persisted
 * to `public.simulations.result`.
 */
export interface AbReport {
  meta: ReportMeta;
  verdict: Verdict;
  ship_list: ShipItem[];
  annotated_screens: AnnotatedScreens;
  persona_split: PersonaSplit[];
  friction_provenance: FrictionProvenance;
  monologue_diff: MonologueDiff[];
  deep_dive?: DeepDive;
}
